// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLineProjectAlarm

#ifndef _SQUARELINEPROJECTALARM_UI_H
#define _SQUARELINEPROJECTALARM_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Checkbox3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_ButtonAlarmOn;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_ButtonAlarmOff;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_lblTime;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
